import { Inter } from "next/font/google";
import "./styles/globals.css";

import Header from "./components/Header/Header.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AuthProvider } from "./context/authContext";
import Footer from "./components/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  flex flex-col items-center`}
      >
        <AuthProvider>
          <Header />
          {children}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
