import { AuthProvider } from './context/authContext';

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { Inter } from "next/font/google";
import "./styles/globals.css";

import Header from "./components/Header.jsx";
import Footer from "./components/Footer.jsx";

const inter = Inter({ subsets: ["latin"] });

import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AuthProvider>
              <Header />
              {children}
              <Footer />
            </AuthProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
